# frozen_string_literal: true

require "rails_helper"
require "pdf-reader"

RSpec.describe HotelPortal::Reports::Exports::PdfReportBuilder do
  let(:hotel) do
    double(
      "hotel", id: 17, name: "Hôtel 東京", address: "1 Jalan Pantai", city: "Kota Kinabalu",
      country: "Malaysia", hotel_time_zone: ActiveSupport::TimeZone["Kuala Lumpur"]
    )
  end

  def extracted_text(content)
    PDF::Reader.new(StringIO.new(content)).pages.map(&:text).join("\n")
  end

  it "builds a branded Unicode report with summary, detail, total, and footer" do
    builder = described_class.new(
      hotel: hotel,
      title: "Contract Report",
      subtitle: "Contract",
      period_label: "22 Jul 2026",
      prepared_by: "Sarah Lim",
      generated_at: Time.utc(2026, 7, 22, 2, 30),
      page_layout: :landscape
    )
    builder.add_header
    builder.add_summary([ [ "Transactions", "1" ], [ "Total Amount", "MYR 25.00" ] ])
    builder.add_table(
      section_title: "Details",
      headers: [ "Guest", "Description", "Amount" ],
      rows: [ [ "测试 Guest", "Dinner", "25.00" ] ],
      numeric_columns: [ 2 ],
      total_row: [ "Total", nil, "25.00" ],
      empty_message: "No rows"
    )

    content = builder.render
    text = extracted_text(content)

    expect(content).to start_with("%PDF")
    expect(text).to include("Contract Report", "Contract", "Hôtel 東京", "1 Jalan Pantai, Kota Kinabalu, Malaysia")
    expect(text).to include(
      "PERIOD", "22 Jul 2026", "GENERATED", "22 Jul 2026, 10:30 AM",
      "PREPARED BY", "Sarah Lim", "Confidential", "Generated by"
    )
    # Stat labels carry their tier by case and tracking, so the strip upcases them.
    expect(text).to include("TRANSACTIONS", "TOTAL AMOUNT", "测试 Guest", "Dinner", "Total")
    expect(text).to match(/Page 1 of \d+/)
    expect(PDF::Reader.new(StringIO.new(content)).pages.first.xobjects).not_to be_empty
  end

  it "renders an informative empty state" do
    builder = described_class.new(hotel: hotel, title: "Empty", period_label: "22 Jul 2026", prepared_by: "Sarah Lim")
    builder.add_header
    builder.add_table(
      section_title: "Details",
      headers: [ "Value" ],
      rows: [],
      numeric_columns: [],
      total_row: [ "Total" ],
      empty_message: "No rows"
    )

    expect(extracted_text(builder.render)).to include("No rows", "Total")
  end

  it "embeds a processed hotel icon alongside the WAStays footer mark" do
    image = Rails.root.join("app/assets/images/logo/icon-logo.png").binread
    processed = double("processed variant", download: image)
    variant = double("variant", processed: processed)
    icon = double("icon", attached?: true)
    allow(icon).to receive(:variant).with(resize_to_limit: [ 96, 96 ], format: :png).and_return(variant)
    allow(hotel).to receive(:icon).and_return(icon)

    builder = described_class.new(hotel: hotel, title: "With Logo", period_label: "22 Jul 2026", prepared_by: "Sarah Lim")
    builder.add_header

    page = PDF::Reader.new(StringIO.new(builder.render)).pages.first
    expect(page.xobjects.size).to be >= 2
  end

  it "omits unavailable branding fields without breaking the report" do
    sparse_hotel = double(
      "hotel", id: 18, name: "Island Stay", address: nil, city: "Semporna", country: nil,
      hotel_time_zone: ActiveSupport::TimeZone["Kuala Lumpur"]
    )
    icon = double("icon", attached?: true)
    allow(icon).to receive(:variant).and_raise(ActiveStorage::FileNotFoundError)
    allow(sparse_hotel).to receive(:icon).and_return(icon)
    allow(Rails.logger).to receive(:warn)

    builder = described_class.new(hotel: sparse_hotel, title: "Sparse", period_label: "22 Jul 2026", prepared_by: "Sarah Lim")
    builder.add_header
    text = extracted_text(builder.render)

    expect(text).to include("Island Stay", "Semporna", "Sparse")
    expect(text).not_to include(", Semporna", "Semporna,")
    expect(Rails.logger).to have_received(:warn).with(/PDF hotel logo unavailable/)
  end

  it "stamps confidentiality and pagination on every page" do
    builder = described_class.new(hotel: hotel, title: "Long Report", period_label: "22 Jul 2026", prepared_by: "Sarah Lim")
    builder.add_header
    builder.add_table(
      section_title: "Details",
      headers: [ "Value" ],
      rows: Array.new(180) { |index| [ "Row #{index + 1}" ] },
      numeric_columns: [],
      total_row: nil,
      empty_message: "No rows"
    )

    pages = PDF::Reader.new(StringIO.new(builder.render)).pages
    expect(pages.size).to be > 1
    pages.each_with_index do |page, index|
      expect(page.text).to include("Confidential", "Generated by", "Page #{index + 1} of #{pages.size}")
    end
  end
end
