# frozen_string_literal: true

require "rails_helper"
require "pdf/reader"
require "stringio"

RSpec.describe Reports::AccountsReceivable::GenerateStatement do
  let(:hotel) do
    create(
      :hotel,
      name: "Hotel ABC Resort",
      address: "Jalan Pantai Cenang",
      city: "Langkawi",
      country: "Malaysia",
      contact_phone: "+60 12-345 6789",
      contact_email: "frontdesk@example.com"
    )
  end
  let(:corporate_account) { create(:account, :corporate, name: "Atlas Travel") }
  let(:relationship) do
    create(
      :hotel_corporate_account,
      hotel: hotel,
      corporate_account: corporate_account,
      credit_currency: "MYR",
      payment_terms_days: 30,
      contact_phone: "+60 19-876 5432",
      billing_address_line1: "Level 3, Lot 8",
      billing_address_line2: "Jalan Lintas",
      billing_city: "Kota Kinabalu",
      billing_state: "Sabah",
      billing_postal_code: "88300",
      billing_country: "Malaysia"
    )
  end
  let!(:contact) { create(:user, :corporate, account: corporate_account, email: "billing@atlas.test") }

  it "renders the booking-invoice-style statement header, ledger, totals, aging, and footer" do
    allow(hotel).to receive(:current_business_date).and_return(Date.new(2026, 6, 30))
    booking = create(:booking, hotel: hotel, confirmation_token: "BK-PDF", currency: "MYR")
    folio = create(:booking_folio, :secondary, booking: booking, hotel: hotel, hotel_corporate_account: relationship, currency: "MYR")
    invoice = create(
      :ar_invoice,
      hotel: hotel,
      booking_folio: folio,
      hotel_corporate_account: relationship,
      invoice_number: 9001,
      amount: 250,
      outstanding_amount: 250,
      currency: "MYR",
      issued_on: Date.new(2026, 6, 5),
      due_on: Date.new(2026, 6, 20)
    )
    create(
      :ar_payment,
      hotel: hotel,
      hotel_corporate_account: relationship,
      amount: 100,
      currency: "MYR",
      reference_number: "BANK-PDF-1",
      received_at: Date.new(2026, 6, 10)
    )
    report = Reports::AccountsReceivable::GenerateStatementRecords.call(
      hotel: hotel,
      hotel_corporate_account: relationship,
      start_date: Date.new(2026, 6, 1),
      end_date: Date.new(2026, 6, 30),
      currency: "MYR"
    )

    with_frozen_time Time.zone.local(2026, 6, 30, 14, 35, 0) do
      pdf = described_class.new(report: report, printed_by: "F. Suhaila").generate
      text = pdf_text(pdf)

      expect_landscape(pdf)
      expect(text).to include("Account Statement")
      expect(text).to include("Hotel ABC Resort")
      expect(text).to include("CORPORATE ACCOUNT")
      expect(text).to include("Atlas Travel")
      expect(text).to include("billing@atlas.test")
      expect(text).to include("+60 19-876 5432")
      expect(text).to include("Contact email", "Contact phone")
      expect(text).not_to include("billing@atlas.test · +60 19-876 5432")
      expect(text).to include("Billing address", "Level 3, Lot 8", "88300 Kota Kinabalu", "Sabah, Malaysia")
      expect(text).to include("Opening Balance")
      expect(text).to include("Period")
      expect(text).to include("01 Jun 2026 - 30 Jun 2026")
      expect(text).to include(invoice.formatted_invoice_number)
      expect(text).to include("BANK-PDF-1")
      expect(text).to include("Statement Summary (MYR)")
      expect(text).to include("Invoice Aging", "As of 30 Jun 2026")
      expect(text).to include("Generated", "Prepared by", "F. Suhaila", "Generated by WAStays.com")
      expect(text).to include("Page 1 of")
      expect(text).to include("Jalan Pantai Cenang, Langkawi, Malaysia")
      expect(text).not_to include("Confidential")
      expect(text).not_to include("Guest Signature")
      expect(text).not_to include("Payment Terms")
      expect(text).to include("Currency", "MYR")
      expect(text).not_to include("NOTES")
      expect(text).not_to include("HOTEL INFORMATION")
      expect(text).not_to include("ACCOUNT DETAILS")
      expect(text).to include("STATEMENT DETAILS")
      expect(text.index("CLOSING BALANCE")).to be < text.index("Invoice Aging")
      expect(text.index("Invoice Aging")).to be < text.index(invoice.formatted_invoice_number)
      expect(text.index(invoice.formatted_invoice_number)).to be < text.index("Statement Summary (MYR)")
      expect(text).not_to include("(DETAIL)")
    end
  end

  it "renders per-invoice line items when detail mode is requested, instead of the flat ledger" do
    allow(hotel).to receive(:current_business_date).and_return(Date.new(2026, 6, 30))
    room_type = create(:room_type, hotel: hotel, name: "Deluxe Room")
    booking = create(:booking, hotel: hotel, confirmation_token: "BK-DETAIL", currency: "MYR", guest_name: "Mr. Detail Guest")
    create(:booking_room, booking: booking, room_type: room_type, room_number: "301")
    folio = create(:booking_folio, :secondary, booking: booking, hotel: hotel, hotel_corporate_account: relationship, currency: "MYR")
    invoice = create(
      :ar_invoice,
      hotel: hotel,
      booking_folio: folio,
      hotel_corporate_account: relationship,
      invoice_number: 9002,
      amount: 120,
      outstanding_amount: 120,
      currency: "MYR",
      issued_on: Date.new(2026, 6, 5),
      due_on: Date.new(2026, 6, 20)
    )
    create(:folio_transaction, booking_folio: folio, transaction_type: :charge, category: "accommodation", amount: 120, posting_date: Date.new(2026, 6, 5), description: "Room Charges")

    report = Reports::AccountsReceivable::GenerateStatementRecords.call(
      hotel: hotel,
      hotel_corporate_account: relationship,
      start_date: Date.new(2026, 6, 1),
      end_date: Date.new(2026, 6, 30),
      currency: "MYR",
      include_invoice_details: true
    )

    pdf = described_class.new(report: report, printed_by: "F. Suhaila", detail: true).generate
    text = pdf_text(pdf)

    expect_landscape(pdf)
    expect(text).to include("Account Statement")
    expect(text).not_to include("(DETAIL)")
    expect(text).to include("Mr. Detail Guest")
    expect(text).to include(invoice.formatted_invoice_number)
    expect(text).to include("301 - Deluxe Room")
    expect(text).to include("Room Charges")
    expect(text).not_to include("Reference")
    expect(text.index("Billing Name")).to be < text.index("Statement Summary")
  end

  it "prints a visible placeholder when the current relationship has no billing address" do
    relationship.update!(
      billing_address_line1: nil,
      billing_address_line2: nil,
      billing_city: nil,
      billing_state: nil,
      billing_postal_code: nil,
      billing_country: nil
    )
    allow(hotel).to receive(:current_business_date).and_return(Date.new(2026, 6, 30))
    booking = create(:booking, hotel:, currency: "MYR")
    folio = create(:booking_folio, :secondary, booking:, hotel:, hotel_corporate_account: relationship, currency: "MYR")
    create(:ar_invoice, hotel:, booking_folio: folio, hotel_corporate_account: relationship, currency: "MYR")
    report = Reports::AccountsReceivable::GenerateStatementRecords.call(
      hotel:, hotel_corporate_account: relationship,
      start_date: Date.new(2026, 6, 1), end_date: Date.new(2026, 6, 30), currency: "MYR"
    )

    text = pdf_text(described_class.new(report:).generate)

    expect(text).to include("Billing address", "Not provided")
  end

  def pdf_text(pdf)
    PDF::Reader.new(StringIO.new(pdf)).pages.map(&:text).join("\n")
  end

  def expect_landscape(pdf)
    PDF::Reader.new(StringIO.new(pdf)).pages.each do |page|
      left, bottom, right, top = page.attributes.fetch(:MediaBox)
      expect(right - left).to be > top - bottom
    end
  end
end
