# frozen_string_literal: true

require "rails_helper"
require "pdf/reader"
require "stringio"

RSpec.describe Reports::AccountsReceivable::GenerateGroupStatement do
  let(:hotel) { create(:hotel, hotel_prefix: "GST") }
  let(:group) { create(:group_booking, hotel:) }
  let(:relationship) { create(:hotel_corporate_account, hotel:) }

  it "renders all non-void group invoices for the payer and currency without creating records" do
    first = ar_invoice_for(booking_for(1), amount: 125)
    second = ar_invoice_for(booking_for(2), amount: 75)
    second.update!(status: "paid", paid_amount: 75, outstanding_amount: 0)
    voided = ar_invoice_for(booking_for(3), amount: 50)
    voided.update!(status: "void")
    ar_invoice_for(booking_for(4), amount: 20, currency: "USD")
    other_group = create(:group_booking, hotel:)
    foreign_group = ar_invoice_for(create(:booking, hotel:, group_booking: other_group), amount: 30)
    other_relationship = create(:hotel_corporate_account, hotel:)
    wrong_payer = ar_invoice_for(booking_for(5), amount: 40, relationship: other_relationship)

    expect do
      pdf = described_class.new(
        hotel:,
        group_booking: group,
        hotel_corporate_account: relationship,
        currency: "MYR",
        printed_by: "Finance User"
      ).generate
      text = PDF::Reader.new(StringIO.new(pdf)).pages.map(&:text).join("\n")

      expect_landscape(pdf)
      expect(text).to include("Group Accounts Receivable Statement")
      expect(text).to include(first.formatted_invoice_number, second.formatted_invoice_number, "200.00")
      expect(text).to include("PREPARED BY", "Finance User", "Generated by WAStays.com", "Page 1 of")
      expect(text).not_to include("Confidential")
      expect(text).not_to include(voided.formatted_invoice_number, foreign_group.formatted_invoice_number, wrong_payer.formatted_invoice_number)
    end.not_to change(ArInvoice, :count)
  end

  it "rejects an empty payer and currency combination" do
    expect { generate(currency: "USD") }.to raise_error(described_class::ValidationError, /No AR invoices/)
  end

  def booking_for(position)
    create(:booking, hotel:, group_booking: group, group_position: position)
  end

  def ar_invoice_for(booking, amount:, currency: "MYR", relationship: self.relationship)
    folio = create(:booking_folio,
      booking:,
      hotel:,
      status: "closed",
      is_primary: false,
      folio_type: "external",
      payer_type: "company",
      currency:,
      hotel_corporate_account: relationship)
    create(:ar_invoice, booking_folio: folio, hotel:, hotel_corporate_account: relationship, amount:, currency:)
  end

  def generate(currency: "MYR")
    described_class.new(
      hotel:,
      group_booking: group,
      hotel_corporate_account: relationship,
      currency:
    ).generate
  end

  def expect_landscape(pdf)
    PDF::Reader.new(StringIO.new(pdf)).pages.each do |page|
      left, bottom, right, top = page.attributes.fetch(:MediaBox)
      expect(right - left).to be > top - bottom
    end
  end
end
