require "rails_helper"

RSpec.describe Reports::Bookings::GenerateVoucher do
  let(:hotel) do
    create(
      :hotel,
      name: "Seaview Hotel",
      fixed_line_number: "088-221 100",
      contact_phone: "+60 12-345 6789",
      contact_email: "stay@seaview.example"
    )
  end
  let(:room_type) { create(:room_type, hotel: hotel, name: "Deluxe") }
  let(:booking) do
    create(:booking,
      hotel: hotel,
      guest_name: "Aisha",
      confirmation_token: "WS-VOUCHER1",
      total_amount: 300.0,
      check_in: Date.new(2026, 5, 1),
      check_out: Date.new(2026, 5, 3),
      hotel_snapshot: { "property_policy" => { "check_in_time" => "3:00 PM", "cancellation_policy" => "No refund" } })
  end

  before do
    create(
      :booking_room,
      booking: booking,
      room_type: room_type,
      subtotal: 300.0,
      room_type_snapshot: { "name" => "Deluxe" },
      nightly_rate_snapshot: {
        "2026-05-01" => { "price" => "150.00", "transaction_code_code" => "RM-DLX" },
        "2026-05-02" => { "price" => "150.00", "transaction_code_code" => "RM-DLX" }
      }
    )
  end

  def pdf_text(pdf)
    PDF::Reader.new(StringIO.new(pdf)).pages.map(&:text).join("\n")
  end

  it "generates a valid PDF binary" do
    pdf = described_class.new(booking).generate

    expect(pdf).to be_a(String)
    expect(pdf.force_encoding("BINARY")[0, 5]).to eq("%PDF-")
    expect(pdf.bytesize).to be > 1500
  end

  it "renders the shared title, party blocks, dense nightly charges, and guest details" do
    booking.update!(
      created_at: Time.zone.local(2026, 7, 17, 12, 0),
      guest_country: "Singapore",
      guest_home_address: "12 Jalan Pantai, Singapore",
      total_amount: 324,
      tax_lines: [ { "name" => "SST", "amount" => 24.0 } ],
      tax_posting_snapshot: {
        "2026-05-01" => [ { "name" => "SST", "amount" => "12.00", "transaction_code_code" => "TX-SST" } ],
        "2026-05-02" => [ { "name" => "SST", "amount" => "12.00", "transaction_code_code" => "TX-SST" } ]
      }
    )

    text = pdf_text(described_class.new(booking).generate)

    expect(text).to include(
      "BOOKING VOUCHER",
      booking.formatted_reservation_number,
      "Confirmation WS-VOUCHER1",
      "CONFIRMED",
      "Fixed line: 088-221 100",
      "Phone: +60 12-345 6789",
      "Email: stay@seaview.example",
      "GUEST DETAILS",
      "Address",
      "12 Jalan Pantai, Singapore",
      "CONTACT DETAILS",
      "STAY DETAILS",
      "Arrival",
      "01 May 2026, 3:00 PM",
      "Departure",
      "03 May 2026, 12:00 PM",
      "2 nights",
      "Guests",
      "2 adults",
      "Booked at",
      HotelPortal::Reports::Exports::PdfTheme.format_time(booking.created_at, hotel.hotel_time_zone),
      "Charges",
      "Net (MYR)",
      "Charges (MYR)",
      "Gross (MYR)",
      "RM-DLX",
      "Night 1 of 2",
      "Night 2 of 2",
      "TX-SST",
      "SST",
      "Total due",
      "324.00",
      "Singapore",
      "Generated by",
      "Page 1 of 1"
    )
    expect(text).not_to include("RESERVATION DETAILS", "Currency", "Check-in time", "Check-out time")
    expect(text).not_to include("Confidential")
  end

  it "renders the total paid and positive balance due from folio transactions" do
    booking.update!(total_amount: 324.0)
    folio = create(:booking_folio, booking: booking, hotel: hotel)
    create(:folio_transaction, booking_folio: folio, transaction_type: :payment, category: "booking_payment", amount: 100.0)

    text = pdf_text(described_class.new(booking).generate)

    expect(text).to include("Payments", "Total payments", "(100.00)", "Balance due", "224.00")
  end

  it "omits balance due when transactions cover the total and guest country is blank" do
    booking.update!(guest_country: nil)
    folio = create(:booking_folio, booking: booking, hotel: hotel)
    create(:folio_transaction, booking_folio: folio, transaction_type: :payment, category: "booking_payment", amount: 300.0)

    text = pdf_text(described_class.new(booking).generate)

    expect(text).to include("Total payments", "(300.00)", "Booking balance settled")
    expect(text).not_to include("Balance due")
  end

  it "shows an overpayment as a credit balance" do
    folio = create(:booking_folio, booking: booking, hotel: hotel)
    create(:folio_transaction, booking_folio: folio, transaction_type: :payment, category: "booking_payment", amount: 400.0)

    text = pdf_text(described_class.new(booking).generate)

    expect(text).to include("Total payments", "(400.00)", "Credit balance", "100.00")
    expect(text).not_to include("Booking balance settled")
  end

  it "renders the cancellation tier table from the booking's own snapshot, with the description beneath" do
    booking.update!(cancellation_policy_snapshot_data: {
      "description" => "Non-refundable during Hari Raya.",
      "refund_processing_days" => 7,
      "refund_method" => "original_payment_method",
      "tiers" => [
        { "days_before_arrival" => 14, "window" => "14+ days before arrival", "charge" => "No charge" },
        { "days_before_arrival" => 0, "window" => "Less than 1 day before arrival", "charge" => "keep 100.00% of total stay" }
      ]
    })

    text = pdf_text(described_class.new(booking).generate)

    expect(text).to include(
      "If cancelled",
      "14+ days before arrival",
      "No charge",
      "Less than 1 day before arrival",
      "keep 100.00% of total stay",
      "Refunds are issued to the original payment method within 7 working days.",
      "Non-refundable during Hari Raya."
    )
    # The prose snapshot is never shown alongside the table it could contradict.
    expect(text).not_to include("No refund")
  end

  it "falls back to the legacy prose for bookings taken before the policy was structured" do
    booking.update!(cancellation_policy_snapshot: "Free cancellation up to 24 hours before arrival")

    text = pdf_text(described_class.new(booking).generate)

    expect(text).to include("Free cancellation up to 24 hours before arrival")
  end

  it "does not count posted room charges as payments" do
    booking.update!(total_amount: 300.0)
    folio = create(:booking_folio, booking: booking, hotel: hotel)
    create(:folio_transaction, booking_folio: folio, transaction_type: :charge, category: "accommodation", amount: 300.0)
    create(:folio_transaction, booking_folio: folio, transaction_type: :payment, category: "booking_payment", amount: 100.0)

    text = pdf_text(described_class.new(booking).generate)

    expect(text).to include("Total payments", "(100.00)", "Balance due", "200.00")
  end

  it "discloses tourism tax separately without including it in total due" do
    booking.update!(
      tourism_tax_amount: 20,
      tourism_tax_collected: false,
      tax_lines: [ { "name" => "Tourism tax", "type" => "tourism_tax", "amount" => "20.00" } ],
      tax_posting_snapshot: {
        "2026-05-01" => [ { "name" => "Tourism tax", "type" => "tourism_tax", "amount" => "10.00" } ],
        "2026-05-02" => [ { "name" => "Tourism tax", "type" => "tourism_tax", "amount" => "10.00" } ]
      }
    )

    text = pdf_text(described_class.new(booking).generate)

    expect(text).to include(
      "Total due",
      "300.00",
      "Excluded from booking total: Tourism tax of MYR 20.00 is payable at the property. " \
        "A separate tourism tax voucher will be provided.",
      "Please present this voucher at check-in."
    )
    expect(text.index("Excluded from booking total")).to be < text.index("Please present this voucher")
    expect(text.scan("Tourism tax").size).to eq(1)
  end

  it "repeats document identity, charge headers, and numbered furniture over a long stay" do
    nights = 30
    booking.update!(check_out: booking.check_in + nights.days, total_amount: nights * 100)
    booking.booking_rooms.sole.update!(
      subtotal: nights * 100,
      nightly_rate_snapshot: nights.times.to_h do |index|
        [ (booking.check_in.to_date + index.days).iso8601, { "price" => "100.00" } ]
      end
    )

    pages = PDF::Reader.new(StringIO.new(described_class.new(booking.reload).generate)).pages

    expect(pages.size).to be > 1
    expect(pages.drop(1).map(&:text).join).to include("Seaview Hotel", "Booking voucher")
    expect(pages.count { |page| page.text.include?("Net (MYR)") && page.text.include?("Charges (MYR)") && page.text.include?("Gross (MYR)") }).to eq(pages.size)
    pages.each_with_index do |page, index|
      expect(page.text).to include("Generated by", "Page #{index + 1} of #{pages.size}")
    end
  end
end
