require "rails_helper"

RSpec.describe Reports::Bookings::GenerateVoucher do
  let(:hotel) do
    create(
      :hotel,
      name: "Seaview Hotel",
      fixed_line_number: "088-221 100",
      contact_phone: "+60 12-345 6789",
      contact_email: "stay@seaview.example"
    )
  end
  let(:room_type) { create(:room_type, hotel: hotel, name: "Deluxe") }
  let(:booking) do
    create(:booking,
      hotel: hotel,
      guest_name: "Aisha",
      confirmation_token: "WS-VOUCHER1",
      total_amount: 300.0,
      check_in: Date.new(2026, 5, 1),
      check_out: Date.new(2026, 5, 3),
      hotel_snapshot: { "property_policy" => { "check_in_time" => "3:00 PM", "cancellation_policy" => "No refund" } })
  end

  before do
    create(
      :booking_room,
      booking: booking,
      room_type: room_type,
      subtotal: 300.0,
      room_type_snapshot: { "name" => "Deluxe" },
      nightly_rate_snapshot: {
        "2026-05-01" => { "price" => "150.00", "transaction_code_code" => "RM-DLX" },
        "2026-05-02" => { "price" => "150.00", "transaction_code_code" => "RM-DLX" }
      }
    )
  end

  def pdf_text(pdf)
    PDF::Reader.new(StringIO.new(pdf)).pages.map(&:text).join("\n")
  end

  it "generates a valid PDF binary" do
    pdf = described_class.new(booking).generate

    expect(pdf).to be_a(String)
    expect(pdf.force_encoding("BINARY")[0, 5]).to eq("%PDF-")
    expect(pdf.bytesize).to be > 1500
  end

  it "renders the shared title, party blocks, and guest details" do
    booking.update!(
      created_at: Time.zone.local(2026, 7, 17, 12, 0),
      guest_country: "Singapore",
      guest_home_address: "12 Jalan Pantai, Singapore"
    )

    text = pdf_text(described_class.new(booking).generate)

    expect(text).to include(
      "BOOKING VOUCHER",
      booking.formatted_reservation_number,
      "Confirmation WS-VOUCHER1",
      "CONFIRMED",
      "Fixed line: 088-221 100",
      "Phone: +60 12-345 6789",
      "Email: stay@seaview.example",
      "GUEST DETAILS",
      "Address",
      "12 Jalan Pantai, Singapore",
      "CONTACT DETAILS",
      "STAY DETAILS",
      "Arrival",
      "01 May 2026, 3:00 PM",
      "Departure",
      "03 May 2026, 12:00 PM",
      "2 nights",
      "Guests",
      "2 adults",
      "Booked at",
      HotelPortal::Reports::Exports::PdfTheme.format_time(booking.created_at, hotel.hotel_time_zone),
      "Singapore",
      "Please present this voucher at check-in.",
      "Generated by",
      "Page 1 of 1"
    )
    expect(text).not_to include("RESERVATION DETAILS", "Currency", "Check-in time", "Check-out time")
    expect(text).not_to include("Confidential")
  end

  # The reason the split exists: a voucher is presented at the desk, and the guest holding
  # it should not be handing their balance over with it.
  it "states no money at all" do
    booking.update!(total_amount: 324.0, tourism_tax_amount: 20, tourism_tax_collected: false)
    folio = create(:booking_folio, booking: booking, hotel: hotel)
    create(:folio_transaction, booking_folio: folio, transaction_type: :payment, category: "booking_payment", amount: 100.0)

    text = pdf_text(described_class.new(booking.reload).generate)

    expect(text).not_to include("Charges", "Payments", "Total due", "Total payments")
    expect(text).not_to include("Balance due", "Credit balance", "Booking balance settled")
    expect(text).not_to include("324.00", "100.00", "224.00")
    expect(text).not_to include("Excluded from booking total")
  end

  it "renders the cancellation tier table from the booking's own snapshot, with the description beneath" do
    booking.update!(cancellation_policy_snapshot_data: {
      "description" => "Non-refundable during Hari Raya.",
      "refund_processing_days" => 7,
      "refund_method" => "original_payment_method",
      "tiers" => [
        { "days_before_arrival" => 14, "window" => "14+ days before arrival", "charge" => "No charge" },
        { "days_before_arrival" => 0, "window" => "Less than 1 day before arrival", "charge" => "keep 100.00% of total stay" }
      ]
    })

    text = pdf_text(described_class.new(booking).generate)

    expect(text).to include(
      "If cancelled",
      "14+ days before arrival",
      "No charge",
      "Less than 1 day before arrival",
      "keep 100.00% of total stay",
      "Refunds are issued to the original payment method within 7 working days.",
      "Non-refundable during Hari Raya."
    )
    # The prose snapshot is never shown alongside the table it could contradict.
    expect(text).not_to include("No refund")
  end

  it "falls back to the legacy prose for bookings taken before the policy was structured" do
    booking.update!(cancellation_policy_snapshot: "Free cancellation up to 24 hours before arrival")

    text = pdf_text(described_class.new(booking).generate)

    expect(text).to include("Free cancellation up to 24 hours before arrival")
  end

  it "renders special requests when the guest made any" do
    booking.update!(special_requests: "High floor, away from the lift.")

    text = pdf_text(described_class.new(booking).generate)

    expect(text).to include("Special requests", "High floor, away from the lift.")
  end

  describe "#render_into" do
    it "draws into a document it does not own and hands back the frame" do
      pdf = Prawn::Document.new(page_size: "A4", margin: HotelPortal::Reports::Exports::PdfTheme::PAGE_MARGIN)
      HotelPortal::Reports::Exports::PdfTheme.configure_font(pdf)

      frame = described_class.new(booking).render_into(pdf)
      frame.stamp_page_furniture

      expect(pdf_text(pdf.render)).to include("BOOKING VOUCHER", "Confirmation WS-VOUCHER1")
    end
  end
end
