# frozen_string_literal: true

require "stringio"

module HotelPortal
  module Reports
    module Exports
      class PdfReportFrame
        FOOTER_Y = -9
        HOTEL_LOGO_SIZE = 44
        WASTAYS_LOGO_WIDTH = 50

        def initialize(pdf:, hotel:, report_name:, period_label:, prepared_by:, period_label_title: "Period", subtitle: nil, generated_at: Time.current)
          @pdf = pdf
          @hotel = hotel
          @report_name = report_name
          @subtitle = subtitle
          @period_label_title = period_label_title
          @period_label = period_label
          @prepared_by = prepared_by
          @generated_at = generated_at
        end

        def draw_header
          draw_hotel_identity
          draw_report_identity
          draw_metadata
        end

        def stamp_footer
          @pdf.repeat(:all) do
            @pdf.stroke_color PdfTheme::COLORS[:border]
            @pdf.line_width 0.5
            @pdf.stroke_horizontal_line 0, @pdf.bounds.width, at: 2
            @pdf.fill_color PdfTheme::COLORS[:muted]
            @pdf.draw_text "Confidential", at: [ 0, FOOTER_Y ], size: 7
            draw_wastays_attribution
          end
          @pdf.number_pages(
            "Page <page> of <total>",
            at: [ @pdf.bounds.width - 90, FOOTER_Y ], width: 90, align: :right, size: 7,
            color: PdfTheme::COLORS[:muted]
          )
        end

        private

        def draw_hotel_identity
          top = @pdf.cursor
          logo = hotel_logo
          text_left = logo ? HOTEL_LOGO_SIZE + 12 : 0

          @pdf.image logo, at: [ 0, top ], fit: [ HOTEL_LOGO_SIZE, HOTEL_LOGO_SIZE ] if logo
          @pdf.fill_color PdfTheme::COLORS[:ink]
          @pdf.text_box @hotel.name.to_s, at: [ text_left, top ], width: @pdf.bounds.width - text_left,
            height: 18, size: 12, style: :bold, overflow: :shrink_to_fit, min_font_size: 9
          @pdf.fill_color PdfTheme::COLORS[:muted]
          @pdf.text_box hotel_address, at: [ text_left, top - 21 ], width: @pdf.bounds.width - text_left,
            height: 24, size: 8, leading: 2, overflow: :shrink_to_fit, min_font_size: 6
          @pdf.move_down [ HOTEL_LOGO_SIZE, 48 ].max
          @pdf.move_down 8
          @pdf.stroke_color PdfTheme::COLORS[:border]
          @pdf.stroke_horizontal_rule
          @pdf.move_down 14
        end

        def draw_report_identity
          @pdf.fill_color PdfTheme::COLORS[:ink]
          @pdf.text @report_name.to_s, size: 16, style: :bold, align: :center,
            overflow: :shrink_to_fit, min_font_size: 11
          if @subtitle.present?
            @pdf.move_down 3
            @pdf.fill_color PdfTheme::COLORS[:muted]
            @pdf.text @subtitle.to_s, size: 9, align: :center
          end
          @pdf.move_down 14
        end

        def draw_metadata
          metadata = [
            [ @period_label_title, @period_label ],
            [ "Generated", generated_label ],
            [ "Prepared by", @prepared_by ]
          ]
          table = @pdf.make_table(
            [ metadata.map(&:first), metadata.map(&:last) ],
            width: @pdf.bounds.width,
            cell_style: { padding: [ 5, 8 ], borders: [], overflow: :shrink_to_fit, min_font_size: 6 }
          )
          table.row(0).style(
            background_color: PdfTheme::COLORS[:primary_light], text_color: PdfTheme::COLORS[:muted],
            size: 7, font_style: :bold, borders: [ :top ], border_color: PdfTheme::COLORS[:border]
          )
          table.row(1).style(
            background_color: PdfTheme::COLORS[:primary_light], text_color: PdfTheme::COLORS[:ink],
            size: 8, borders: [ :bottom ], border_color: PdfTheme::COLORS[:border]
          )
          table.draw
          @pdf.fill_color PdfTheme::COLORS[:ink]
          @pdf.move_down 16
        end

        def hotel_address
          [ @hotel.try(:address), @hotel.try(:city), @hotel.try(:country) ].compact_blank.join(", ")
        end

        def generated_label
          @generated_at.in_time_zone(@hotel.hotel_time_zone).strftime("%d %b %Y, %I:%M %p")
        end

        def hotel_logo
          return unless @hotel.respond_to?(:icon) && @hotel.icon.attached?

          variant = @hotel.icon.variant(resize_to_limit: [ 96, 96 ], format: :png).processed
          StringIO.new(variant.download)
        rescue StandardError => error
          Rails.logger.warn("PDF hotel logo unavailable for hotel #{@hotel.id}: #{error.class}: #{error.message}")
          nil
        end

        def draw_wastays_attribution
          logo_path = Rails.root.join("app/assets/images/logo/long-logo.png")
          center = @pdf.bounds.width / 2.0
          label_width = 48
          group_width = label_width + WASTAYS_LOGO_WIDTH + 5
          left = center - (group_width / 2.0)
          @pdf.draw_text "Generated by", at: [ left, FOOTER_Y ], size: 7
          @pdf.image logo_path, at: [ left + label_width + 5, FOOTER_Y + 7 ], width: WASTAYS_LOGO_WIDTH if File.exist?(logo_path)
        end
      end
    end
  end
end
